[build]
  publish = "src/pages"

# 将 / 路由回退到 index.html (用于 SPA 或 HTML5 History 模式)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 静态资源重定向：确保 src/assets 下的文件能被访问到
[[redirects]]
  from = "/assets/*"
  to = "/src/assets/:splat"
  status = 200
  force = true

# 保证 components 的 header/footer 可通过 w3-include-html 加载
[[redirects]]
  from = "/components/*"
  to = "/src/components/:splat"
  status = 200
  force = true

# 安全头配置
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com;
      img-src 'self' data: https:;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      connect-src 'self';
      frame-ancestors 'none';
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# 缓存控制 - 静态资源长期缓存
[[headers]]
  for = "/src/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = true

# HTML 文件每次请求都重新验证
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 字体文件缓存优化
[[headers]]
  for = "/src/assets/**/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 防止目录列表暴露
[[headers]]
  for = "/*/"
  [headers.values]
    X-Robots-Tag = "noindex"