[build]
  # 直接部署源码中的页面目录
  publish = "src/pages/"

# 静态资源重定向规则（核心配置）
[[redirects]]
  from = "/assets/*"
  to = "/src/assets/:splat"  # :splat 捕获通配符内容
  status = 200
  force = true  # 强制覆盖现有路径

# SPA 路由回退（修正路径）
[[redirects]]
  from = "/*"
  to = "/index.html"  # 指向发布目录中的 index.html
  status = 200

# 安全与缓存全局设置
[[headers]]
  for = "/*"
  [headers.values]
    # 强制 HTTPS + HSTS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    
    # 内容安全策略（CSP）- 根据实际资源调整
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://fonts.googleapis.com;
      img-src 'self' data: https:;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      connect-src 'self';
      frame-ancestors 'none';
    """
    
    # 安全头
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# 静态资源缓存策略（JS/CSS/图片等）
[[headers]]
  for = "/src/assets/*"  # 匹配资源路径
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = true

# HTML 文件缓存策略
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 浏览器缓存优化（字体文件）
[[headers]]
  for = "/src/assets/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 防止目录列表暴露
[[headers]]
  for = "/*/"
  [headers.values]
    X-Robots-Tag = "noindex"