[build]
  publish = "src/"

# 将 / 路由回退到 index.html (用于 SPA 或 HTML5 History 模式)
[[redirects]]
  from = "/*"
  to = "/pages/index.html"
  status = 200

# 静态资源重定向：确保 src/assets 下的文件能被访问到
[[redirects]]
  from = "../assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# 保证 components 的 header/footer 可通过 w3-include-html 加载
[[redirects]]
  from = "../components/*"
  to = "/components/:splat"
  status = 200
  force = true